### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by crysan** [ShogoMizumoto/ZDepthShadowLayout#1]
Please dependencies compile

**Comment by TurKurT656** [comment]
+1, This is great Lib
would be great if we can use this lib with gradle :)

**Comment by sho5nn** [comment]
@crysan 
@TurKurT656 
OK, I modified README.md. Please confirm. :)

**Comment by TurKurT656** [comment]
TnQ, I will Test It right now :)

**Comment by TurKurT656** [comment]
It works like a charm, thnx

**Comment by crysan** [comment]
Ty!
