### ISSUE TITLE
Great!!, but...the background of the shadow is not translucent. T^T

### ISSUE THREAD

**Issue by drakeet** [ShogoMizumoto/ZDepthShadowLayout#4]
I set a ZDepthShadowLayout to a Toolbar, but as you see below: Shadow line can be seen clearly, it can't be vaguely revealed under the words, this is not a perfect effect, can't accept T^T

![device-2015-04-02-195315](https://cloud.githubusercontent.com/assets/5214214/6963587/98d59474-d973-11e4-849c-e53c0703d5ce.png)

**Comment by sho5nn** [comment]
@drakeet 
I want to see this layout xml file. plz.

**Comment by drakeet** [comment]
I have reverted it, just like this:

``` xml
<FrameLayout ...>

    <FrameLayout ...>
        <me.drakeet.seashell.widget.MultiSwipeRefreshLayout .../>
    </FrameLayout> 

    <ZDepthShadowLayout ...>
        <Toolbar .../>
    </ZDepthShadowLayout ...>

</FrameLayout> 
```

**Comment by drakeet** [comment]
I found your demo root layout is `RelativeLayout`, but I used `FrameLayout`...maybe I should have a try to use `RelativeLayout`

**Comment by tinybright** [comment]
@drakeet your moe avatar!
